In [131]:
import pandas as pd
import numpy as np
import os

In [132]:
df = pd.read_csv("C:\\Users\\hp\\Desktop\\spam.csv")

In [133]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [134]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [135]:
df['spam']=df['Category'].apply(lambda x:1 if x=='spam'else 0)

In [136]:
df.shape

(5572, 3)

In [137]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [138]:
from sklearn.model_selection import train_test_split

In [139]:
X_train,x_test,y_train,y_test=train_test_split(df.Message,df.spam,test_size=0.2)

In [140]:
X_train.shape

(4457,)

In [141]:
x_test.shape

(1115,)

In [142]:
type(x_test)

pandas.core.series.Series

In [143]:
X_train[:4]

5187                                   WHAT TIME U WRKIN?
4228                      Buy one egg for me da..please:)
3018    One of the joys in lifeis waking up each daywi...
1393    Thk shld b can... Ya, i wana go 4 lessons... H...
Name: Message, dtype: object

In [144]:
type(y_train)

pandas.core.series.Series

In [145]:
y_train[:4]

5187    0
4228    0
3018    0
1393    0
Name: spam, dtype: int64

In [146]:
type(X_train.values)

numpy.ndarray

In [147]:
from sklearn.feature_extraction.text import CountVectorizer

v=CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)

X_train_cv

<4457x7804 sparse matrix of type '<class 'numpy.int64'>'
	with 59649 stored elements in Compressed Sparse Row format>

In [148]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [149]:
X_train_cv.shape

(4457, 7804)

In [150]:
v.get_feature_names_out()[725]

'89555'

In [151]:
v.get_feature_names_out().shape

(7804,)

In [ ]:
dir(v)

In [153]:
X_train_np=X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [154]:
np.where(X_train_np[0]!=0)

(array([6962, 7534, 7681], dtype=int64),)

In [155]:
print(X_train.head())

5187                                   WHAT TIME U WRKIN?
4228                      Buy one egg for me da..please:)
3018    One of the joys in lifeis waking up each daywi...
1393    Thk shld b can... Ya, i wana go 4 lessons... H...
4353                    Hows the pain dear?y r u smiling?
Name: Message, dtype: object


In [156]:
print(X_train)

5187                                   WHAT TIME U WRKIN?
4228                      Buy one egg for me da..please:)
3018    One of the joys in lifeis waking up each daywi...
1393    Thk shld b can... Ya, i wana go 4 lessons... H...
4353                    Hows the pain dear?y r u smiling?
                              ...                        
1428    THING R GOOD THANX GOT EXAMS IN MARCH IVE DONE...
1236    Your opinion about me? 1. Over 2. Jada 3. Kusr...
4926               Ok... Let u noe when i leave my house.
2847                     Wat time u finish ur lect today?
1860            What's up. Do you want me to come online?
Name: Message, Length: 4457, dtype: object


In [158]:
X_train[:4][5187]

'WHAT TIME U WRKIN?'

In [159]:
X_train_np[0][5187]

0

In [160]:
from sklearn.naive_bayes import MultinomialNB

In [161]:
model=MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [162]:
x_test_cv=v.transform(x_test)

In [163]:
from sklearn.metrics import classification_report
y_pred=model.predict(x_test_cv)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       958
           1       1.00      0.94      0.97       157

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [164]:
emails=["Your gonna have to pick up a $1 burger for yourself on your way home. I can't even move. Pain is killing me.",
       "As a valued customer, I am pleased to advise you that following recent review of your Mob No. you are awarded with a £1500 Bonus Prize, call 09066364589",
        "I like you peoples very much:) but am very shy pa.",
        "Congrats! 1 year special cinema pass for 2 is yours. call 09061209465 now! C Suprman V, Matrix3, StarWars3, etc all 4 FREE! bx420-ip4-5we. 150pm. Dont miss out!"]
emails_count=v.transform(emails)
model.predict(emails_count)

array([0, 1, 0, 1], dtype=int64)

In [172]:
from sklearn.pipeline import Pipeline
clf=Pipeline([
    ('vectorizer',CountVectorizer()),'nb',MultinomialNB()
])
clf.fit(X_train,y_train)

In [174]:
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer

# Correctly define the pipeline with tuples for each step
clf = Pipeline([
    ('vectorizer', CountVectorizer()),  # Step 1: Text vectorization
    ('nb', MultinomialNB())              # Step 2: Classifier
])

# Fit the model on the training data
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [177]:
y_pred=clf.predict(x_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       958
           1       1.00      0.94      0.97       157

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115

